name: 重邮疫情打卡

on:
    workflow_dispatch:
    schedule:
        - cron: "01 04 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                python-version: 3.8

            - name: "安装依赖包requests"
              run: pip install  requests
            - name: "安装依赖包hyper"
              run: pip install  hyper

            - name: "运行 自动重邮打卡"
              run: python report.py
             
