name: 重邮疫情打卡

on:
    workflow_dispatch:
    schedule:
        - cron: "01 04 * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                python-version: 3.8
            - name: "升级pip"
              run: python -m pip install --upgrade pip

            - name: "安装依赖包"
              run: pip install -r requests

            - name: "运行 哔咔漫画自动打哔咔"
              run: python report.py
             
